Make upgrade to Laravel 5.7 backward compatible
BRACKETS-by-TRIAD/admin-auth pull request #9
Opened 2018-10-30 12:29 UTC by palypster

@dejwCake what do you say if we override also all the method that make calls to the method which signature was changed? This way it could be backward compatible (with all laravel version - 5.5, 5.6 and 5.7) What do you think?

In new big upcoming update of admin-auth we would address this issue differently. Huh?

2018-11-01 08:44 UTC, dejwCake requested changes

2018-11-01 08:44 UTC, dejwCake commented on src/Http/Controllers/Auth/ResetPasswordController.php
> +            ? $this->sendResetResponse($request, $response)
In my opinion, this will not work, because the method signature is different than in trait.

2018-11-01 08:44 UTC, dejwCake commented on src/Http/Controllers/Auth/ForgotPasswordController.php
> +            ? $this->sendResetLinkResponse($request, $response)
Same here, in trait SendsPasswordResetEmails, this method sendResetLinkResponse in L5.5 looks like protected function sendResetLinkResponse($response), but you override it with protected function sendResetLinkResponse(Request $request, $response). The signature is different. But I might be mistaken. It needs to be tested.

2018-11-01 11:10 UTC, palypster commented on src/Http/Controllers/Auth/ForgotPasswordController.php
> +            ? $this->sendResetLinkResponse($request, $response)
It seems this is actually the way the traits were designed in PHP - no checks of signature. I have just tested the simple code:
```
<?php

class Foo {}
class Bar {}

trait A {

    public function foo(Foo $foo) {
        echo "Foo from A\n";
    }

}

class B {
    use A;

    public function foo(Foo $foo, Bar $bar) {
        echo "Foo from B\n";   
    }
}

$b = new B;
$b->foo(new Foo, new Bar);
```
and it works.

2018-11-06 10:27 UTC, dejwCake approved these changes

2018-11-06 10:29 UTC, merged